thingsboard/thingsboard-gateway

- pom.xml
> support java 9 compiler

- src/main/resources/opc-config.json
(cherry picked from commit c1c75e97865604b78ccb6558e86170ceb8d73e74)
> Minor fix to opc-config.json

- src/main/java/org/thingsboard/gateway/extensions/mqtt/client/conf/mapping/MqttJsonConverter.java
- src/main/java/org/thingsboard/gateway/util/converter/BasicJsonConverter.java
Added the possibility to map timestamp and timestamp format using MQTT extension
> Timestamp and format mapping for MQTT

- src/main/java/org/thingsboard/gateway/service/gateway/MqttGatewayService.java
- src/main/java/org/thingsboard/gateway/util/converter/BasicJsonConverter.java
Repair gateway receive attributes return value
> #135 Repair gateway receive attributes return value

- src/main/java/org/thingsboard/gateway/extensions/mqtt/client/MqttBrokerMonitor.java
> Fix MQTT extension configuration update did not delete old configuration. #138

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
This commit enables:
- Using attribute wildcards for MQTT attribute updates
- Sending more than a value in attribute updates, enabling
subscription for attribute groups
Tested using:
`
...
"attributeUpdates":
[
{
"deviceNameFilter": "MY_DEV_.*",
"attributeFilter": ".*",
"topicExpression": "test/${deviceName}/attributes",
"valueExpression": "{\"${attributeKey}\":\"${attributeValue}\"}"
}
],
...
`
`
{
"device" : "MY_DEV_0",
"data" :
{
"a" : 0,
"b" : 1
}
}
`
> More general handling of attribute updates in MQTT connector

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
1 - Disconnect requests were handled only if no connection requests
handlers were defined (if ... elif ...)
2 - If message topic contained a device name defined by
deviceNameTopicExpression, incoming messages were treated
as connection requests even if they were disconnection requests
3 - Devices already known to the gateway were not served during
connection requests => ThingsBoard did not send RPCs and updates
for them
4 - Added some comments, which is always good :smile: 
You can use connect/disconnect requests instructions from gateway guides:
pre-commit, the the aforementioned errors happen.
> Fixed bugs in MQTT connector (connect/disconnect requests)

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
- thingsboard_gateway/gateway/tb_gateway_service.py
Hi,
I performed a full cleanup of the MQTT connector; moreover, I added a couple handy options.
1 - It is now possible to specify mqtt QoS level for telemetry, attribute updates and so on
2 - It is now possible to ask for shared attributes values, instead of only subscribing for changes
3 - Code style is now more or less uniform in the whole file
4 - I inserted comments in the whole file
5 - Corrected a bug in disconnect method
You can test this version using a config file like this:
`
{
"broker": {...},
"mapping": [{..., "subscriptionQos": 1}],
"connectRequests": [{..., "subscriptionQos": 1}],
"disconnectRequests": [{..., "subscriptionQos": 1}],
"attributeUpdates": [],
"attributeRequests": [{
"topicFilter": "up/attr/+/requests/+",
"subscriptionQos": 1,
"deviceNameTopicExpression": …
> Slibutti mqtt

- thingsboard_gateway/config/logs.conf
Converter logs instance was using connector.log file
> fix logger_converter to log into converter.log file

- thingsboard_gateway/connectors/opcua/opcua_connector.py
KEPServer EX6  support.  I think more opcServer need this.
> some crappy opc_service support

- thingsboard_gateway/connectors/opcua/opcua_connector.py
Bug Fix: if an OPC-UA source generates more than one value change in the same polling cycle, the platform receives only the  last one. Moreover, gateway's memory grows indefinitely.
Solution: flush event set and send all data to platform,
so data_to_send doesn't grow indefinitely in case of more than one value change
per cycle.
NOTE: possible performance improvement: use a map to store only one event per
variable to reduce frequency of messages to platform.
>  giusguerrini, 2020-09-24:

- thingsboard_gateway/connectors/opcua/opcua_connector.py
When I tried to subscribe to thousands of nodes, the node subscription became slower and slower, because the previously subscribed node subscription data was sent over, which occupied resources. Changing to the final batch subscription can significantly improve.
> batch sub opc ua node

- thingsboard_gateway/connectors/opcua/opcua_connector.py
Hello,
in OPC UA Gateway i have now new syntax "${$DisplayName}", ${$BrowseName}", "${$NodeId.Identifier}" to get devicename from current node without searching for OPC UA variable.
"mapping": [
{
"deviceNodePattern": "Root.Objects.Station_1300.U\\d+$",
"deviceNamePattern": "Bostation_${$DisplayName}",
"deviceTypePattern": "Bo",
"attributes": [
{ "key": "Name", "path": "${Name}" }
],
"timeseries": [
{ "key": "Wateralarm", "path": "${HwLes}" }
]
}
]
This matches Root.Objects.Station_1300.U01, Root.Objects.Station_1300.U02, ...
Because the OPC UA Scan is verry slow (may be 300 ms for one tag) i optimise the scan.
My new function is "get_node_path(self, node)" to get the full path os a OPC UA node. The old one node.get_path() is verry slow and dose not Work with deep pathes (e.g. …
> OPCUA new syntax for "${$DisplayName}", ... optimise OPCUA scan

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
- thingsboard_gateway/gateway/tb_gateway_service.py
Added some logging
Solved subscription to None topic
Solved error when searching rpc topic among registered ones
Solved bug that caused nacks to be sdent to Thingsboard after acks
> [MQTT] Rpc fixes

- thingsboard_gateway/connectors/opcua/opcua_connector.py
please take a look at
https://github.com/thingsboard/thingsboard-gateway/issues/680
> issue with __search_attribute_update_variables

- thingsboard_gateway/connectors/opcua/opcua_connector.py
Streamlined creating a client and connecting to a OPC-UA server.
Fixes:
* State inconsistency between the initial created client and client's created on a reconnect
* Always try to disconnect before creating a new client, otherwise the server might leak resources (you might for instance get 'BadTooManySessions')
* `load_type_definitions()` also on a reconnect
> OPCUA: Streamlined creating a client and connection to OPC-UA server.

- thingsboard_gateway/connectors/modbus/bytes_modbus_uplink_converter.py
modified bits decoding to have the correct bit order
> Update bytes_modbus_uplink_converter.py to correct bit order in decoding bits

- thingsboard_gateway/connectors/opcua/opcua_connector.py
cf : https://github.com/thingsboard/thingsboard-gateway/issues/724
> writing an opc ua int32 value fails

- thingsboard_gateway/connectors/opcua/opcua_connector.py
Added uri parameter for the general section in opcua.json file.
> Added application_uri parameter for OPC-UA Connector

- thingsboard_gateway/tb_client/tb_gateway_mqtt.py
content may have no device filed when deal topic 'GATEWAY_ATTRIBUTES_TOPIC'
> fix: add device field check of content

- thingsboard_gateway/config/rest.json
- thingsboard_gateway/config/socket.json
- thingsboard_gateway/connectors/rest/rest_connector.py
- thingsboard_gateway/connectors/socket/socket_connector.py
- Socket Connector
- REST Connector
> Added Attribute Request functionality for Connectors

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
- thingsboard_gateway/connectors/rest/rest_connector.py
- thingsboard_gateway/connectors/socket/socket_connector.py
- thingsboard_gateway/tb_client/tb_gateway_mqtt.py
> Added ability to request multiple shared attributes

- thingsboard_gateway/config/mqtt.json
- thingsboard_gateway/config/rest.json
Updated `attributeRequests` section of config files for MQTT and REST Connectors
> Updated config files

- thingsboard_gateway/grpc_connectors/modbus/__init__.py
- thingsboard_gateway/grpc_connectors/modbus/bytes_modbus_uplink_converter.py
- thingsboard_gateway/grpc_connectors/modbus/modbus_connector.py
- thingsboard_gateway/grpc_connectors/modbus/slave.py
- thingsboard_gateway/grpc_connectors/mqtt/mqtt_connector.py
- thingsboard_gateway/grpc_connectors/opcua/__init__.py
- thingsboard_gateway/grpc_connectors/opcua/opcua_connector.py
- thingsboard_gateway/grpc_connectors/opcua/opcua_uplink_converter.py
> Added GRPC Connectors

- thingsboard_gateway/extensions/serial/custom_serial_connector.py
Reverts thingsboard/thingsboard-gateway#869
> Revert "Serial connector: Load device config from device array "

- thingsboard_gateway/extensions/serial/custom_serial_connector.py
Reverts thingsboard/thingsboard-gateway#874
> Revert "Revert "Serial connector: Load device config from device array ""

- thingsboard_gateway/connectors/opcua/opcua_connector.py
Fixed syntax for importing custom converter
> Fixed import_module for custom converter in opcua_connector

- thingsboard_gateway/connectors/modbus/modbus_connector.py
- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
- thingsboard_gateway/connectors/rest/rest_connector.py
- thingsboard_gateway/connectors/socket/socket_connector.py
- MQTT Connector
- REST Connector
- Socket Connector
- Modbus Connector
> Added reserved get/set methods for connectors

- tests/converters/test_mqtt_json_uplink_converter.py
- thingsboard_gateway/connectors/mqtt/json_mqtt_uplink_converter.py
- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
- thingsboard_gateway/connectors/mqtt/mqtt_uplink_converter.py
Data from my broker has the following format:
```
[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]
```
With this PR my custom converter gets the whole array and covert its based on index of value and pre-defined mapping rules. Without these changes the converter gets values one by one.
> Let mqtt converter to process array data by its own.

- thingsboard_gateway/gateway/tb_gateway_service.py
> Fix and improve data repack algorithm.

- thingsboard_gateway/config/tb_gateway.yaml
It would be great to re-check if the others configuration parameters are present in *tb_gateway.yaml*
> Explicitly set maxPayloadSizeBytes in gateway configuration.

- thingsboard_gateway/connectors/opcua_asyncio/opcua_connector.py
The OPCUA asyncio connector was creating 1 subscription object per variable/node. However, some OPCUA servers have a limit on the amount of subscription objects/handles per session. Note, subscriptions is not the same as monitored items/variables.
Additionally I've improved the resetting of nodes on problems (e.g. when they are removed from the OPCUA tree) and the feedback in the log.
Let me know if anything should be changed.
> opcua_asyncio: Use 1 subscription object per connection + improved feedback & reset on node problems

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
Converter type should not be empty.
> Revert "Fixed getting custom converter"

- thingsboard_gateway/config/request.json
- thingsboard_gateway/connectors/request/json_request_downlink_converter.py
- thingsboard_gateway/connectors/request/request_connector.py
fixed https://github.com/thingsboard/thingsboard-gateway/issues/1071
> Request connector bug

- thingsboard_gateway/gateway/tb_client.py
Example config (Server generated access token):
```yaml
...
provisioning:
type: AUTO
provisionDeviceKey: c5abnbjxkcnopuffvcn3
provisionDeviceSecret: ehxirt44od02cvj4rikm
```
Example config (Access Token):
```yaml
...
provisioning:
type: ACCESS_TOKEN
provisionDeviceKey: c5abnbjxkcnopuffvcn3
provisionDeviceSecret: ehxirt44od02cvj4rikm
```
Example config (Basic MQTT):
```yaml
...
provisioning:
type: MQTT_BASIC
provisionDeviceKey: c5abnbjxkcnopuffvcn3
provisionDeviceSecret: ehxirt44od02cvj4rikm
```
Example config (X509):
```yaml
...
provisioning:
type: X509_CERTIFICATE
provisionDeviceKey: c5abnbjxkcnopuffvcn3
provisionDeviceSecret: ehxirt44od02cvj4rikm
caCert: tb-server-chain.pem
```
> Added Gateway Provisioning

- thingsboard_gateway/config/mqtt.json
- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
This feature let's using stateful custom MQTT converters that is being shared between different topics.
Docs PR [#1019](https://github.com/thingsboard/thingsboard.github.io/pull/1019)
> Added on demand caching of custom MQTT converters.

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
This is continuation of [#1090](https://github.com/thingsboard/thingsboard-gateway/pull/1090) and I hope the end.
Rename `cached` configuration key to `sharedGlobal`.
Add `sharedId` to provide more granularity in sharing custom MQTT converters.
Don't forget about [pull request for documentation](https://github.com/thingsboard/thingsboard.github.io/pull/1019).
> [FEATURE] Add sharing id instead of global converter cache for MQTT connector.

- thingsboard_gateway/gateway/tb_gateway_service.py
This was slowing down the rate of data pushes significantly.
> Remove sleep per data point pushed

- thingsboard_gateway/gateway/tb_gateway_service.py
bug tb_gateway_service.py -> __form_statistics
> bug tb_gateway_service.py -> __form_statistics

- tests/converters/test_mqtt_json_uplink_converter.py
- thingsboard_gateway/connectors/mqtt/json_mqtt_uplink_converter.py
- thingsboard_gateway/tb_utility/tb_utility.py
1. Add support of spaced keys.
2. Use `type` configuration option to convert incoming data to another data type.
> Fixed and improved default JSON MQTT uplink converter.

- requirements.txt
Reverts thingsboard/thingsboard-gateway#1318
> Revert "Changed requirements.txt"

- generate_deb_package.sh
- make_packages.sh
- setup.py
- thingsboard_gateway/tb_utility/tb_updater.py
- version.py
Details in https://github.com/thingsboard/thingsboard-gateway/issues/984
> [FIX] Added version file.

- docker/Dockerfile
> docker python12 and cleanup

- thingsboard_gateway/connectors/can/can_connector.py
- thingsboard_gateway/connectors/odbc/odbc_connector.py
- thingsboard_gateway/connectors/xmpp/xmpp_connector.py
> Added new GET/SET RPC

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
> Fix RPC request in MQTT Connector

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
Added ability to use deviceName placeholder for rpc value and shared attr update value expressions and removed quotes for string in shared attributes.
> Added ability to use additional placeholders in MQTT connector

- thingsboard_gateway/connectors/modbus/bytes_modbus_uplink_converter.py
Improved implementation of #1563, Added rounding for all floats to 6 numbers after point and added "round" parameter.
> Added float rounding to Modbus Uplink Converter

- thingsboard_gateway/connectors/rest/json_rest_uplink_converter.py
- thingsboard_gateway/connectors/rest/rest_connector.py
Add display of converted data inside rest convertor with info status
> feat: add info to display logs to rest convertor

- thingsboard_gateway/connectors/ftp/ftp_connector.py
Added more logs for ftp connector, improved log messages for existing.
> feature: added more logs, improve existing logs messages

- thingsboard_gateway/connectors/ftp/ftp_connector.py
Fixed ftp connector to correctly process all required rpc methods
> fix:fix rpc methods in ftp connector

- thingsboard_gateway/gateway/entities/converted_data.py
Reverts thingsboard/thingsboard-gateway#1824
> Revert "Removed compute-expensive operation in converted data"

- setup.py
> Updated python required version

- thingsboard_gateway/config/request.json
- thingsboard_gateway/connectors/request/json_request_downlink_converter.py
- thingsboard_gateway/connectors/request/request_connector.py
Same bugs fixed as in REST JSON downlink converter
> Bugfixs for Request connector JSON downlink converter

- thingsboard_gateway/config/rest.json
- thingsboard_gateway/connectors/rest/json_rest_downlink_converter.py
- thingsboard_gateway/connectors/rest/rest_connector.py
Closes https://github.com/thingsboard/thingsboard-gateway/issues/1682
> Bugfixes for REST connector JSON downlink converter

- tests/unit/connectors/opcua/test_server_side_rpc.py
- thingsboard_gateway/connectors/opcua/device.py
- thingsboard_gateway/connectors/opcua/opcua_connector.py
Add more explicit logic for handling not supported input formats for device rpc
> Added more explicit logic for incorrect device rpc types

- thingsboard_gateway/connectors/opcua/opcua_connector.py
Fix error on attribute update and opcua server disconnection.
> Fixed error with incorrect attribute update after OPC-UA server disconnnect

- thingsboard_gateway/connectors/opcua/opcua_connector.py
I came across this error during development.
> Corrected number of arguments for logger

- thingsboard_gateway/connectors/knx/knx_connector.py
Fix error with incorrect rpc request handling
> Fixed error with incorrect rpc request handling

- thingsboard_gateway/connectors/mqtt/mqtt_connector.py
- thingsboard_gateway/gateway/tb_gateway_service.py
Fix missing device reply for MQTT connector RPC.
> Fixed two-way RPC processing
