thingsboard/thingsboard-gateway

build.gradle
pom.xml
src/main/java/org/thingsboard/gateway/extensions/modbus/DefaultModbusService.java
src/main/java/org/thingsboard/gateway/extensions/modbus/ModbusClient.java
src/main/java/org/thingsboard/gateway/extensions/modbus/ModbusDevice.java
src/main/java/org/thingsboard/gateway/extensions/modbus/ModbusService.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/ModbusConfiguration.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/ModbusExtensionConstants.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/ModbusServerConfiguration.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/mapping/DataMapping.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/mapping/DeviceMapping.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/mapping/TagMapping.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/transport/ModbusIpTransportConfiguration.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/transport/ModbusRtuTransportConfiguration.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/transport/ModbusTcpTransportConfiguration.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/transport/ModbusTransportConfiguration.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/transport/ModbusUdpTransportConfiguration.java
src/main/java/org/thingsboard/gateway/service/TenantServiceRegistry.java
src/main/resources/modbus-config.json

The service supports the following Modbus protocols: RTU, ASCII, TCP, UDP.
The service can simultaneously communicate with several Modbus servers, each of them you can configure separately.
The supported functions:
- Read Coils (code 1)
- Read Discrete Inputs (code 2)
- Read Multiple Holding Registers (code 3)
- Read Input Registers (code 4)

Modbus service

---

src/main/java/org/thingsboard/gateway/extensions/mqtt/client/listener/MqttDeviceStateChangeMessageListener.java
src/main/java/org/thingsboard/gateway/service/gateway/MqttGatewayService.java

Fixed 2 issues where related to deviceType in MQTT Gateway service:
- deviceType not inserted into MQTT message that being sent to upstream Thingsboard backend.
- Evaluation condition of deviceTypeTopicExpression and deviceTypeJsonExpression is incorrect.

Fixing deviceType in MQTT not propagate up to Thingsboard 

---

src/main/java/org/thingsboard/gateway/extensions/mqtt/client/conf/mapping/MqttJsonConverter.java

Using a deviceType**Topic**Expression with mqtt/json mapping always leads to errors, since the deviceType**Json**Expression was used.
This fixes this issue.

Mqtt/json mapping: use correct pattern for deviceType TopicExpression

---

src/main/java/org/thingsboard/gateway/service/gateway/MqttGatewayService.java

The right request payload should be `{"sharedKeys":"configuration"}` instead of `{"shared":"configuration"}`.
TB will return all attributes if the request payload was wrong, and once the response payload bigger than  8192 bytes, Gateway will be crashed.
```
[nioEventLoopGroup-2-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: null
at nl.jk5.mqtt.MqttPingHandler.channelRead(MqttPingHandler.java:34)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
...
```

Fixed get configuration request payload

---

pom.xml
src/main/java/org/thingsboard/gateway/extensions/modbus/ModbusClient.java
src/main/java/org/thingsboard/gateway/extensions/modbus/ModbusDevice.java
src/main/java/org/thingsboard/gateway/extensions/modbus/ModbusDeviceAware.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/ModbusExtensionConstants.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/mapping/DeviceMapping.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/mapping/PollingTagMapping.java
src/main/java/org/thingsboard/gateway/extensions/modbus/conf/mapping/TagValueMapping.java
src/main/java/org/thingsboard/gateway/extensions/modbus/rpc/RpcProcessor.java
src/main/java/org/thingsboard/gateway/extensions/modbus/util/ModbusUtils.java
src/main/java/org/thingsboard/gateway/service/gateway/MqttGatewayService.java
src/main/java/org/thingsboard/gateway/util/JsonTools.java

Also fix the case when Modbus device that has the atribute and telemetry item with the same name cannot save both of them but only atribute.

Multiple tags write via Server-side RPC for Modbus extension

---

src/main/java/org/thingsboard/gateway/extensions/opc/OpcUaDevice.java
src/main/java/org/thingsboard/gateway/extensions/opc/OpcUaDeviceAware.java
src/main/java/org/thingsboard/gateway/extensions/opc/OpcUaServerMonitor.java
src/main/java/org/thingsboard/gateway/extensions/opc/rpc/RpcProcessor.java
src/main/java/org/thingsboard/gateway/extensions/opc/util/OpcUaUtils.java
src/main/java/org/thingsboard/gateway/service/gateway/MqttGatewayService.java
src/main/java/org/thingsboard/gateway/util/JsonTools.java

1. Multiple tags write.
2. Supported OPC types  `Boolean, Byte, Char, Short, Word, DWord, Long, LLong, QWord, Float, Double, Date, String`.
KEPServerEx 6.6
[TB man page](https://thingsboard.io/docs/user-guide/rpc/#server-side-rpc-api) on Server-side RPC format.
**method**: `write`
**params**: _see below_
```json
{
"TagName1": <value1>,
"TagName2": <value2>
}
```
1. Global error
```json
{
"error": "<error_description>"
}
```
2. Success or fail on tag.
```json
{
"TagName1": "ok|<error_description>",
"TagName2": "ok|<error_description>"
}
```
```json
{
"BooleanTag": true,
"DoubleTag": 3.14,
"LongTag": 12345,
"StringTag": "Hello World!",
"DateTagMillisInGmtTimeZone": 1543922564000,
"DateTagAsString": "2018-12-06 12:40:50.123 PST",
"Group.SubGroup.WordTag": 3456
}
```
```json
{
"error": …
```

Multiple tags write via Server-side RPC for OPC UA extension

---

thingsboard_gateway/tb_utility/tb_utility.py

fix - can not load custom converters & connectors from /var/lib/thingsboard_gateway/extensions/

fix - can not load extension from /var/lib/thingsboard_gateway/extensions/

---

thingsboard_gateway/connectors/opcua/opcua_connector.py

When OPC UA connect lost, the connector execute self.client.connect() , however the  connect() method  got Exception not ConnectionRefusedError. so it will not reconncet the server again.

fix OPC UA lose connect

---

for_build/etc/thingsboard-gateway/config/ble.json
for_build/etc/thingsboard-gateway/config/mqtt.json
for_build/etc/thingsboard-gateway/config/request.json
for_build/etc/thingsboard-gateway/config/rest.json
for_build/etc/thingsboard-gateway/config/snmp.json
for_build/etc/thingsboard-gateway/config/tb_gateway.yaml
generate_deb_package.sh

when i run `sudo ./generate_deb_package.sh` command to generate .deb file, 
`sudo cp -r thingsboard_gateway/extensions for_build/etc/thingsboard-gateway/extension` command creates another extension folder in **for_build/etc/thingsboard-gateway/extensions** . ->  **for_build/etc/thingsboard-gateway/extensions/extensions**
Also this sitiuation is same for copying config folder command:  `sudo cp -r thingsboard_gateway/command for_build/etc/thingsboard-gateway/command`
I fixed these two copy command and update latest config files under **for_build** folder. This issue may not occur on your platform. So, this may an unnecessary pull request.
OS : Ubuntu 20.04.1 LTS

fix copy command

---

thingsboard_gateway/gateway/tb_gateway_service.py

don't call constructor if the connector is not loaded, log a warning instead

don't call constructor if the connector is not loaded

---

thingsboard_gateway/connectors/modbus/modbus_connector.py

Added extra call to __available_functions so that when changing multiple registers using modbus function_code 15 or 16, the code uses "values" (line 301)  instead of "value" (line 297)

Update modbus_connector.py to solve the issue related with "missing 1 required positional argument: 'values'"

---

thingsboard_gateway/tb_utility/tb_utility.py

Recently changed data validation function does its checks by treating
attributes/values as they were dictionaries; however, they are lists
of dictionaries.
data["telemetry"].get("ts") is bound to fail: the correct check would be
data["telemetry"][i].get("ts"), for each element i.
Signed-off-by: Simone Libutti <simone.libutti@ibtsystems.it>

Bugfix: validation always fails: 'str' object has no attribute 'get'

---

thingsboard_gateway/connectors/mqtt/mqtt_connector.py

Fixed several problems:
- __subscribes_sent growing indefinitely with each RPC request
- RPC requests sometime sent before MQTT client was actually subscribed for the response
- RPC requests sometime sent before gateway registered the corresponding response topic in its internal RPC list
Added some logging and cleaned up the code a bit.

Improvements to RPC handling in MQTT connector

---

MANIFEST.in
setup.py

These changes ensure that the example config files and the license text are included in the source distribution uploaded to pypi. They were tested by running `python3 setup.py sdist` and examining the generated tarball.
I recommend making a minor release if these changes are accepted so that the new files show up in a release on pypi.

Source distribution fixes

---

for_build/etc/systemd/system/thingsboard-gateway.service

* Only start the service if the config exists. This avoids wasting time in an infinite restart loop if thingsboard-gateway is unconfigured.
* Start the service in the thingsboard_gateway home directory.

Improvements to systemd service file

---

thingsboard_gateway/connectors/bacnet/bacnet_connector.py
thingsboard_gateway/connectors/ble/ble_connector.py
thingsboard_gateway/connectors/can/can_connector.py
thingsboard_gateway/connectors/ftp/ftp_connector.py
thingsboard_gateway/connectors/odbc/odbc_connector.py
thingsboard_gateway/connectors/request/request_connector.py

@zbeacon Updated the fix for the connector type issue discussed in #548.  Still not sure whether the other change is desired or not so I decided to create a new PR that does not include it.
Here is the description of the connector type issue again:
Within _rpc_request_handler in the TBGatewayService, a connector's type is compared to the module initially attached to a method to determine whether to forward the content to the server side rpc handler.  Without the correct property "_connector_type" specified on a connector, you will receive an error saying "[Connector Class] object has no attribute _connector_type."  Below is the relevant code from the _rpc_request_handler.

Fix connector types

---

thingsboard_gateway/gateway/tb_gateway_service.py

''2022-01-05 00:12:55' - ERROR - tb_gateway_service - 1007 - '>' not supported between instances of 'list' and 'int''
Traceback (most recent call last):
File "/Users/ysimonx/Developpement/tb-gateway/env/lib/python3.9/site-packages/thingsboard_gateway/gateway/tb_gateway_service.py", line 1001, in __load_persistent_devices
if len(devices[device_name] > 2) and device_name not in self.__renamed_devices:
TypeError: '>' not supported between instances of 'list' and 'int'
) seems to be at a wrong place

typo error

---

thingsboard_gateway/connectors/opcua/opcua_connector.py

based on https://github.com/thingsboard/thingsboard-gateway/issues/698
when I start tb-gateway, with only 15 mapping elements on a remote opcua server, it takes 3 minutes before being ready
the get_node_path is done several times, is slow, is called many times for the same node : let's cache it
with this improvement, on my computer, instead of 3 minutes, the tb gateway is ready in 30 secondes

Update for performance improvement when mapping OPCUA nodes

---

thingsboard_gateway/connectors/opcua/opcua_connector.py
thingsboard_gateway/connectors/opcua/opcua_converter.py
thingsboard_gateway/connectors/opcua/opcua_uplink_converter.py

In the OPC-UA protocol a source timestamp is available to record/reflect when a variable was sampled by the server, see SourceTimestamp in https://reference.opcfoundation.org/v104/Core/docs/Part4/7.7.3/. This timestamp should be used for recording the data in thingsboard, because:
The SourceTimestamp accurately reflects when the value was created. Any data transfer or processing time delays will not affect the measument.
Multiple synchronized value updates (e.g. in case of a complex control loop) will be recorded with the same timestamp in thingsboard.
Closes https://github.com/thingsboard/thingsboard-gateway/issues/702

OPCUA: Use SourceTimestamp

---

thingsboard_gateway/connectors/opcua/opcua_connector.py

based on https://github.com/thingsboard/thingsboard-gateway/issues/741
where i did not manage to connect an OPC UA Server with username and password
because uacrypto is not found
let's install "cryptography"

name 'uacrypto' is not defined"

---

thingsboard_gateway/connectors/opcua/opcua_connector.py

cf https://github.com/thingsboard/thingsboard-gateway/issues/735
in my opcua.json, i have a key for both telemetry and attributes
${User Registers\.cPURE\.Fan\.DeltaP_100}
but, opc ua connector matches this key with both
User Registers.cPURE.Fan.DeltaP_10
and
User Registers.cPURE.Fan.DeltaP_100
we should not select this node (DeltaP_10 !!), 
this node is selected because the "scanning" process selects node of type variable, even when a partial match is done.

opc ua : mapping telemetry and/or attributes fails

---

thingsboard_gateway/connectors/opcua/opcua_connector.py

Currently, the except block didn't import the Node module from the opcua library, thus leading to possible errors when referred (e.g., line 551).

Fixed Node module import for opcua library

---

thingsboard_gateway/connectors/rest/rest_connector.py

Response in REST Connector can have 3 variants of configuration now:
1. default response (without extra configuration, return only HTTP Status Code);
2. hardcoded response body, for this option you have to specify a new section and 2 new optional parameters as in the example below:
3. (ADVANCED) remote response that will return by ThingsBoard. 
1. To configure that variant you have to specify a new section in the config file as in the example below:
2. Configure RuleChain in ThingsBoard:
1. Yellow Rule Node. 
2. Blue Rule Node

Added 'Remote Response' functionality for REST Connector

---

tests/connectors/test_can_connector.py
tests/data/can/ts_and_attr.json
thingsboard_gateway/connectors/can/can_connector.py

Without this PR multiple command configuration (see example below) for the same nodeId doesn't work at all:
```
"timeseries":
[ {
"key": "INVCH_Bdc_bExporting",
"nodeId": 419419328,
"isExtendedId": true,
"command": "0:1:little:0",
"value": "2:1:int",
"expression": "value"
}, {
"key": "18FFD4C0_Index3_Byte1",
"nodeId": 419419328,
"isExtendedId": true,
"command": "0:1:little:3",
"value": "1:1:int",
"expression": "value"
}
]
}
```

Fix ignoring more than one command configurations.

---

docker/Dockerfile
docker/requirements.txt

created a "requirements.txt" file mentioning required dependencies and
further installing dependencies using pip way with "--no-cache-dir" flag.
further, using "--no-cache-dir" flag in pip install ,make sure downloaded packages
by pip don't cached on system . This is a best practice which make sure
to fetch from repo instead of using local cached one . Further , in case
of Docker Containers , by restricting caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: …

use `--no-cache-dir` flag to `pip` in dockerfiles to save space

---

thingsboard_gateway/extensions/serial/custom_serial_connector.py

**Description:** 
The PR resolves three issues:

Serial connector: Load device config from device array 

---

thingsboard_gateway/connectors/mqtt/mqtt_connector.py
thingsboard_gateway/gateway/tb_gateway_service.py

- Added a separate queue for incoming messages to increase the input message stream
- Decreased default value of maxPayloadSizeBytes parameter to exclude TB client disconnecting (If you are using local ThingsBoard, you can increase this parameter but don't forget to increase the max MQTT packet size in the TB)

Fixed calculating data size and optimized MQTT Connector

---

thingsboard_gateway/gateway/tb_gateway_service.py

When Thingsboard sends a gateway_device_deleted RPC to the gateway, the device is removed from persistent devices file and from local __connected_devices array.
The device is still present in local __saved_devices array, so if I recreate a device with the same name, the first time it sends a message to Thingsboard the persistent devices file is not updated since that name is already present in __saved_devices
```python
def add_device(self, device_name, content, device_type=None):
if device_name not in self.__saved_devices:
device_type = device_type if device_type is not None else 'default'
self.__connected_devices[device_name] = {**content, "device_type": device_type}
self.__saved_devices[device_name] = {**content, "device_type": device_type}
self.__save_persistent_devices() …
```

Fix devices list management after a delete_device RPC from thingsboard

---

thingsboard_gateway/connectors/opcua_asyncio/opcua_connector.py

The check to determine if authentication should be done with a certificate was based on the wrong dict. The check for authentication by username was set correctly (see directly below).

opcua_asyncio: fixes cert.PEM auth_settings call

---

thingsboard_gateway/connectors/modbus/modbus_connector.py

Fix the bug of modbus connector initialization failure due to unclear definition of pymodbus version number.

Fix: define pymodbus packages dependency version

---

thingsboard_gateway/connectors/opcua_asyncio/device.py
thingsboard_gateway/connectors/opcua_asyncio/opcua_connector.py

Most NodeId types are very loose (especially Opaque/ByteString), hence the regex should be very inclusive as well.
See https://documentation.unified-automation.com/uasdkhp/1.4.1/html/_l2_ua_node_ids.html for more information.

opcua_asyncio: Fixes node regex + improved log messages

---

thingsboard_gateway/connectors/opcua_asyncio/opcua_connector.py
thingsboard_gateway/connectors/opcua_asyncio/opcua_uplink_converter.py

* Catch more exceptions that indicate a node is unavailable / does not exit
* Load ExtensionObject / struct type definitions from the server
* Send ExtensionObjects as string
* Unwrap LocalizedText objects
* Serialize VariantType.DateTime as ISO formatted string

opcua-asyncio: Support ExtensionObject / struct, LocalizedText and DateTime

---

thingsboard_gateway/connectors/opcua_asyncio/opcua_connector.py

The NodeId has 4 supported formats (https://documentation.unified-automation.com/uasdkhp/1.4.1/html/_l2_ua_node_ids.html), hence it's better to use the NodeId.to_string() method.
Resolves subscription bug where only the initial value would come through, opcua.json excerpt:
```python
"timeseries": [
{
"key": "is_opcua_connected",
"path": "${ns=1;s=OpcUaServers.MyMockup.ServerStatus}"
},
]
```

opcua_asyncio: use NodeId.to_string

---

thingsboard_gateway/config/statistics/statistics_linux.json

Previous commands are not available for linux.

Updated commands in linux statistics file

---

thingsboard_gateway/config/request.json
thingsboard_gateway/connectors/request/json_request_downlink_converter.py
thingsboard_gateway/connectors/request/request_connector.py

Provided a more flexible way to parse the HTTP server response in the RPC section.
**Renamed params:**
`valueExpression` -> `requestValueExpression`
**New params:**
`responseValueExpression`
Example of new configuration:
```json
"serverSideRpc": [
{
"deviceNameFilter": ".*",
"methodFilter": "getValue",
"requestUrlExpression": "api/states",
"responseTimeout": 1,
"httpMethod": "GET",
"requestValueExpression": "${params}",
"responseValueExpression": "${temp}",
"timeout": 0.5,
"tries": 3,
"httpHeaders": {
"Content-Type": "application/json"
}
},
```

Added responseValueExpression RPC param for Request Connector

---

thingsboard_gateway/connectors/modbus/modbus_connector.py
thingsboard_gateway/connectors/modbus/slave.py

Added TLS support for Modbus TCP Connection (both Gateway as master and Gateway as a slave)
Example configuration for Gateway as master:
```json
{
"master": {
"slaves": [
{
"host": "127.0.0.1",
"port": 5021,
"type": "tcp",
"method": "socket",
"tls": {
"certfile": "./cert.ca",
"keyfile": "./client.key",
"password": "some_password",
"server_hostname": "localhost"
},
"timeout": 35,
...
```
Example configuration for Gateway as a slave:
```json
"slave": {
"type": "tcp",
"security": {
"certfile": "./cert.ca",
"keyfile": "server.key",
"password": "some_password",
"reqclicert": false
},
"host": "127.0.0.1",
...
```

Added TLS support for Modbus TCP Connection

---

thingsboard_gateway/tb_utility/tb_loader.py

This is to allow installing bytecode only, for example on embedded systems.

Load .pyc modules

---

for_build/etc/thingsboard-gateway/extensions/mqtt/custom_mqtt_uplink_converter.py
for_build/etc/thingsboard-gateway/extensions/request/custom_request_uplink_converter.py
for_build/etc/thingsboard-gateway/extensions/serial/custom_serial_converter.py
thingsboard_gateway/connectors/ble/bytes_ble_uplink_converter.py
thingsboard_gateway/connectors/ble/hex_bytes_ble_uplink_converter.py
thingsboard_gateway/connectors/socket/bytes_socket_uplink_converter.py
thingsboard_gateway/extensions/mqtt/custom_mqtt_uplink_converter.py
thingsboard_gateway/extensions/request/custom_request_uplink_converter.py
thingsboard_gateway/extensions/serial/custom_serial_converter.py
thingsboard_gateway/grpc_connectors/socket/bytes_socket_uplink_converter.py

Fix as indicated in #1103 
The value returned by a converter must not be a reference to a static variable. Instead, in this project the default converters use a class variable (`self.dict_result`) to process the received message, and return it at the end. 
So if 2 different messages are queued in `__converted_data_queue` while `__send_to_storage` thread is in its 0.2s sleep, when it wakes up it found a queue of size 2 but both elements have the same reference, whose value is both times the last value assigned to that variable (the last converted message).
The solution is to use a local variable inside the convert function (`dict_result` instead of `self.dict_result`).

Changed the default converters to use local instead of class variables

---

thingsboard_gateway/storage/sqlite/sqlite_event_storage.py

If `Database.process` called from `SQLiteEventStorage.put` handled the request then everything worked. If the `Database.process` running in the `Database` thread handled it then the `Database.process` called from `SQLiteEventStorage.put` would stall waiting for a request to handle.

Fix a race condition in the Sqlite storage which caused all data to stop

---

thingsboard_gateway/tb_utility/tb_utility.py

Resolves: https://github.com/thingsboard/thingsboard-gateway/issues/1227, https://github.com/thingsboard/thingsboard-gateway/issues/1221
This tries to make progress on the error described in https://github.com/thingsboard/thingsboard-gateway/issues/1221
The root cause seems to be that after `pip install` in a subprocess the module in not added to the "context" in which the script was initially started in. Users hence have to "restart" the script to make the module discoverabled.
I found a way where this restart is no necessary which is essentially a copy from here:
- https://stackoverflow.com/a/24773951
- https://docs.python.org/3/library/site.html 
This is how I tested my changes:
```sh
docker build -t local-gateway docker && docker run local-gateway
```

Refresh `sys.path` after lib install

---

thingsboard_gateway/connectors/opcua/opcua_connector.py

To fix this [issue](https://github.com/thingsboard/thingsboard-gateway/issues/1249).

Include sub variables

---

tests/connectors/opcua/test_opcua_connector.py
thingsboard_gateway/connectors/opcua/opcua_connector.py
thingsboard_gateway/connectors/opcua/opcua_uplink_converter.py

Timeseries with nodeid paths containing `\\` in the string part failed with `re.error bad escape \... at position ...`. The `fullmatch(path, config)` would compile the `path` part as a regex, but cannot be assumed to be correctly escaped (hence the `re.error`). Upon closer inspection the rather complicated code can be removed completely by storing the `information` with the subscription when it is first made. Functionality from configuration pov should be unchanged/equivalent.
Test configuration:
```
"timeseries": [
{
"key": "MachineRt_Error_Status",
"path": "${ns=2;s=MachineRt\\Error\\Status}"
},{
"key": "MachineRt_Cycle_Status",
"path": "${ns=2;s=MachineRt\\Cycle\\Status}"
}]
```
Tested with several small OPCUA servers.

opcua: Fixes issues with computing "information" based on path

---

thingsboard_gateway/connectors/rest/rest_connector.py
thingsboard_gateway/connectors/socket/socket_connector.py

- [Fixed argument type for run_app in REST Connector](https://github.com/thingsboard/thingsboard-gateway/commit/2cf1aa915483a328b8fdeeb718a872f34229e82f)
- [Implemented reusing Socket connector address](https://github.com/thingsboard/thingsboard-gateway/commit/e0cf1b26bc1d2489bd08262ba0320819048f1941)

Minor fixes for Socket and REST connectors

---

thingsboard_gateway/gateway/tb_gateway_service.py

A little bit confused, is it designed to allow only one rpc at any given time?
If multi rpc are allowed, then even code got fixed with this pull request,  if two rpc lauched for the same control but different device with the same topic, the rpc request in progress still got overlapped.

fixbug:the rpc request in progress got replaced by the new rpc request

---

thingsboard_gateway/tb_utility/tb_utility.py

This will fix issue #1316  and #1326 so that you can parse json paths with colons in key names with the json converter and data converion to bool is working as well based on the string value like `True` or `False`

Fix issue 1316 and 1326

---

thingsboard_gateway/connectors/opcua_asyncio/opcua_connector.py

```json
"mapping": [
{
"deviceNodePattern": "Root\\.0:Objects\\.3:Simulation",
"deviceNamePattern": "Device asd",
"attributes": [
{
"key": "humidity_dup",
"path": "${ns=3;i=1004}"
}
],
"timeseries": [
{
"key": "humidity",
"path": "${3:Sawtooth}"
},
{
"key": "humidity_sub",
"path": "${Test\\.Counter\\.CounterSubVar}"
}
],
```

Added node browser name format support for OPC-UA

---

thingsboard_gateway/connectors/mqtt/mqtt_connector.py

When subscribing to topics with retain flag set, the mqtt connector can receive all retained messaged since last connection.
Under the broker section in the mqtt json configuration file, two keys have been introduced for MQTT v5. 
- **cleanStart** which must be false for the buffering to work and 
- **sessionExpiryInterval** which must be greater than 0. 
Example configuration for MQTT v5:
```
"broker": {
"name": "Default Local Broker",
"host": "127.0.0.1",
"port": 1883,
"clientId": "ThingsBoard_gateway",
"version": 5,
"cleanStart": false,
"sessionExpiryInterval": 604800,
"maxMessageNumberPerWorker": 10,
"maxNumberOfWorkers": 100,
"sendDataOnlyOnChange": false,
"security": {
"type": "basic",
"username": "user",
"password": "password"
}
``` 
When using MQTT v3, similar behavior can be …

MQTT connector buffering

---

build_docker.sh

build docker script added. requirement for asyncua added
the docker tag is dynamically set with a style like:
VERSION_TAG="${BRANCH_NAME}-${COMMIT_ID}"
head is https://github.com/thingsboard/thingsboard-gateway/pull/1501

build docker script added. requirement for asyncua added

---

thingsboard_gateway/tb_utility/tb_utility.py

Data of devices that use a dash in the key of the JSON payload can not be properly extracted at the moment, as the regular expression does not allow dashes. 
A concrete example: We have devices reading data from smart meters, which send OBIS codes as key.
Example OBIS code: 1-0:1.8.0

Allow filtering keys with dashes (-)

---

thingsboard_gateway/storage/sqlite/database.py
thingsboard_gateway/tb_utility/tb_gateway_remote_configurator.py

If a record already exists in the db messages table, then it first executes the delete sql but does not commit yet, then starts another SQLiteEventStorage instance at [#tb_gateway_remote_configurator.py:346](https://github.com/thingsboard/thingsboard-gateway/blob/36c04c290cf55096ac562032e16b15711897558f/thingsboard_gateway/tb_utility/tb_gateway_remote_configurator.py#L346)  i.e., another sqlite database connection, and again executes the the same delete sql, so the result is a locked database exception.
This exception can be avoided by adding either `self.db.commit()` or `self._gateway._event_storage.stop()`.
I think this could also solve this issue: https://github.com/thingsboard/thingsboard-gateway/issues/1446#issue-2381660977

Fix sqlite database is locked

---

for_build/DEBIAN/postinst
for_build/DEBIAN/preinst
generate_deb_package.sh
setup.py
thingsboard_gateway/gateway/tb_gateway_service.py
thingsboard_gateway/version.py

Hello,
I’d like to contribute to the custom RPC importing functionality for the gateway.
For a long time, I've wanted to enhance the gateway by adding more RPC methods that can be used for local network hardware communication or third-party integration, without exposing the rpcRemoteShell feature. This will provide a secure and controlled way to manage the gateway remotely.
Additionally, I’ve included some minor fixes related to the generation of the .deb package.

custom rpc execution

---

thingsboard_gateway/tb_utility/tb_handler.py

In case of using `TB_GW_LOGS_PATH` env variable, wrong log filename is constructed

[FIX] Use path separator, instead of separator of paths.

---

thingsboard_gateway/connectors/ftp/ftp_connector.py
thingsboard_gateway/connectors/ftp/ftp_uplink_converter.py
thingsboard_gateway/connectors/ftp/path.py
thingsboard_gateway/connectors/rest/rest_connector.py
thingsboard_gateway/connectors/socket/socket_connector.py
thingsboard_gateway/connectors/socket/socket_decorators.py

Fixed reserved GET/SET rpc method

---

thingsboard_gateway/tb_utility/tb_logger.py

Windows use a '\' and not '/' so logger will crash with the old path split

Fixed issue with logger on Windows

---

.dockerignore

The rules currently defined in the .dockerignore file do not exclude anything. You can check it with:
```sh
docker run --rm --entrypoint /bin/bash thingsboard/tb-gateway:latest -c 'ls -la /'
```
This PR fixes [#1590](https://github.com/thingsboard/thingsboard-gateway/issues/1590).
```sh
docker run --rm --entrypoint /bin/bash mbotezatu/tb-gateway:latest -c 'ls -la /'
```

Exclude everything except needed files from docker build context

---

thingsboard_gateway/connectors/mqtt/mqtt_connector.py

Fixed MQTT connector which wrongly assumed keys "tls" were present inside broker["security"] instead of "certificates" and the keys "caCert", "privateKey", "cert" instead of the paths inside the keys: "pathToCACert", "pathToPrivateKey" and "pathToClientCert".
The TLS has been tested and not it works, previously it could not authenticate with certificates.

Fixed TLS authentication for MQTT connector

---

thingsboard_gateway/connectors/mqtt/json_mqtt_uplink_converter.py
thingsboard_gateway/gateway/constants.py

Added a new configuration parameter `useReceivedTs` that allows using the same received timestamp for all timeseries data points within a single message. This helps maintain consistency in timestamp values across related measurements that are received together.
The constant `USE_RECEIVED_TS_PARAMETER = "useReceivedTs"` was added to support this feature.
- Added new constant `USE_RECEIVED_TS_PARAMETER = "useReceivedTs"` in constants.py
- When enabled, the received timestamp will be used for all timeseries data points in a message instead of individual timestamps
- This helps maintain time consistency across related measurements received in a single message
- Ensures all related measurements within a message have the same timestamp
- Prevents time skew between measurements that logically …

Add useReceivedTs option for consistent timestamp handling

---

thingsboard_gateway/connectors/request/request_connector.py

removed the brackets. Otherwise an error occurred. See also "Binary Response Content": https://requests.readthedocs.io/en/latest/user/quickstart/#response-content

fix syntax of response.content

---

thingsboard_gateway/connectors/bacnet/bacnet_connector.py
thingsboard_gateway/connectors/bacnet/device.py

Device address support the following formats:
Local:
- 192.168.1.160:65340
- 192.XXX.1.160:65340
- 192.168.X.160:65340
- 192.168.X.XXX:65340
- 192.XXX.1.160
Local Broadcast to `255.255.255.255`
Remote:
- 11:10.20.XX.30
- 11:10.20.XX.30:65340
Remote Broadcast to `11:*`
Global:
- X:10.20.30.40:65340
- - X:10.20.30.40
Global Broadcast to `*:*`

Added address pattern support for BACnet

---

thingsboard_gateway/connectors/bacnet/application.py
thingsboard_gateway/connectors/bacnet/bacnet_connector.py
thingsboard_gateway/connectors/bacnet/device.py
thingsboard_gateway/connectors/bacnet/entities/bacnet_device_details.py

Added additional variables for BACnet device connected through router:
- routerId
- routerName
- routerAddress
- routerVendorId
Configuration example:
```json
"deviceNameExpression": "BACnet Device ${routerId} ${routerName} ${routerVendorId} ${routerAddress} ${objectName} ${objectId}"
```
Created device:

Add ability to use router vars for BACnet devices connected through router

---

thingsboard_gateway/connectors/opcua/opcua_connector.py

Configuration examples:
```json
{
"deviceNodePattern": "Root\\.Objects\\.Simulation",
"deviceNodeSource": "path",
"deviceInfo": {
"deviceNameExpression": "Device OPCUA ${ns=3;i=1008}",
"deviceNameExpressionSource": "path",
"deviceProfileExpression": "Device",
"deviceProfileExpressionSource": "constant"
}
```
Result:
```json
{
"deviceNodePattern": "Root\\.Objects\\.Simulation",
"deviceNodeSource": "path",
"deviceInfo": {
"deviceNameExpression": "Device OPCUA ${ns=3;i=1008} ${ns=3;i=1009}",
"deviceNameExpressionSource": "path",
"deviceProfileExpression": "Device",
"deviceProfileExpressionSource": "constant"
}
```
Result:

Added identifier support for device name/profile expression

---

thingsboard_gateway/connectors/mqtt/json_mqtt_uplink_converter.py

in json_mqtt_uplink_converter.py
Resolve #1834

fix: remove code that prevented usage of custom timestamp

---

thingsboard_gateway/config/bacnet.json
thingsboard_gateway/config/rest.json
thingsboard_gateway/connectors/bacnet/bacnet_connector.py
thingsboard_gateway/connectors/bacnet/foreign_application.py
thingsboard_gateway/connectors/request/request_connector.py
thingsboard_gateway/connectors/rest/rest_connector.py

With commit https://github.com/thingsboard/thingsboard-gateway/pull/1856/commits/9fe25156f21cb09a9147fe6024c393ddd63a6910 it is possible to register foreign device to support remote BACnet networks.
If `foreignDevice.address` is defined in config and not an empty string the functionality is activated.
```json
{
"foreignDevice": {
"address": "0.0.0.0",
"ttl": 900
},
}
```

features for BACnet connector, REST connector, Request connector

---

thingsboard_gateway/connectors/mqtt/mqtt_connector.py

Fix: ThingsBoard uses default value when device profile is set to a custom constant

Fix for constant device profile expression parsing failure in MQTT

---

thingsboard_gateway/config/mqtt.json
thingsboard_gateway/connectors/mqtt/mqtt_connector.py

Adds support to configure keepalive used by PAHO client in MQTT connector.
```json
"broker": {
"keepAlive": 60
},
```

Support for PAHO client keepalive in MQTT connector

---

thingsboard_gateway/config/request.json
thingsboard_gateway/connectors/request/request_connector.py

Unpack data if `dataUnpackKey` is defined in config
```json
{
"mapping": [
{
"dataUnpackKey": "device"
}
]
}
```
This allows to unpack JSON responses that have final data at a sub key
```json
{
"device": [...]
}
```

Added data unpack functionality in Request connector

---

tests/unit/service/test_storage.py

Remove unnecessary test assertions for sqlite database rotation storage due to possible errors on test machine

remove unnecessary test assertions for sqlite database rotation storage

---

tests/unit/connectors/opcua/test_server_side_rpc.py
thingsboard_gateway/connectors/opcua/entities/rpc_request.py

fixed logic for parsing resevred rpc methods with different delimiters

fix logic for parsing arguments with different delimiter

---

thingsboard_gateway/connectors/ble/ble_connector.py
thingsboard_gateway/connectors/ble/device.py

1. Fix BLE advertisement discovery by making only single instance of BleakScanner.
2. Cleanly cancel scanner/device tasks and disconnect on shutdown to prevent races and missed beacons.

Fixed discovering advertising beacons
